// <auto-generated />
using System;
using CoreGameAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreGameAPI.Migrations
{
    [DbContext(typeof(SandboxContext))]
    [Migration("20211026160632_AddSandboxElements")]
    partial class AddSandboxElements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("CoreGameAPI.Models.SandboxElement", b =>
                {
                    b.Property<int>("SandboxElementKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("SandboxElementStyleKey")
                        .HasColumnType("int");

                    b.HasKey("SandboxElementKey");

                    b.HasIndex("SandboxElementStyleKey");

                    b.ToTable("SandboxElements");
                });

            modelBuilder.Entity("CoreGameAPI.Models.SandboxElementStyle", b =>
                {
                    b.Property<int>("SandboxElementStyleKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.HasKey("SandboxElementStyleKey");

                    b.ToTable("SandboxElementStyles");
                });

            modelBuilder.Entity("CoreGameAPI.Models.SandboxElement", b =>
                {
                    b.HasOne("CoreGameAPI.Models.SandboxElementStyle", "SandboxElementStyle")
                        .WithMany()
                        .HasForeignKey("SandboxElementStyleKey");

                    b.Navigation("SandboxElementStyle");
                });
#pragma warning restore 612, 618
        }
    }
}
